#!/bin/bash
echo Running pre-push hook
echo - Verify Swift Package Version -
# Verify if swift package is updated
./gradlew verifySwiftPackageVersion

# If the packaged is outdated, generate an updated one and push
if [ $? -ne 0 ]; then
 echo Update KMM Swift Package.
 ./gradlew shared:updateSwiftPackage

 # Push the updated swift package
 branch_name="$(git rev-parse --abbrev-ref HEAD)"
 git add Kurrency-*.zip Package.swift Kurrency.xcframework
 git commit -m "Update swift package"
 git fetch
 git push origin "$branch_name"
 exit 1
fi