#!/bin/bash
echo “Running pre-push hook”
echo “- Build KMM Swift Package -”
./gradlew verifyLibraryVersion
if [ $? -ne 0 ]; then
 echo “Build KMM Swift Package.”
 ./gradlew shared:createSwiftPackage
 git add Kurrency-*.zip Package.swift Kurrency.xcframework
 git commit -m "Generate swift package"
 git push --no-verify
 exit 1
fi